---
- hosts: abrizer
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  gather_facts: yes
  vars:
    - ansible_user: vagrant
  roles:
    - role: basic-setup
    - role: weareinteractive.environment
      environment_config:
        PATH: /usr/local/bento4/bin:/usr/bin:/usr/local/bin
    - role: apache
    - role: ffmpeg
    - role: rvm.ruby
      rvm1_rubies:
        - 2.3.3
      rvm1_bundler_install: True
      rvm1_user: "{{ansible_user}}"
      rvm1_rvm_version: 'stable'
      rvm1_autolib_mode: 3
    - role: bento4
    - role: audiowaveform
      ansible_user: vagrant
